---
custom_categories:
- name: RxSwift
  children:
  - AnyObserver
  - Cancelable
  - ConnectableObservableType
  - Deprecated
  - Disposable
  - Errors
  - Event
  - GroupedObservable
  - ImmediateSchedulerType
  - Observable
  - ObservableConvertibleType
  - ObservableType+Extensions
  - ObservableType
  - ObserverType
  - Reactive
  - Rx
  - RxMutableBox
  - SchedulerType
- name: RxSwift/Concurrency
  children:
  - AsyncLock
  - Lock
  - LockOwnerType
  - SynchronizedDisposeType
  - SynchronizedOnType
  - SynchronizedSubscribeType
  - SynchronizedUnsubscribeType
- name: RxSwift/Disposables
  children:
  - AnonymousDisposable
  - BinaryDisposable
  - BooleanDisposable
  - CompositeDisposable
  - Disposables
  - DisposeBag
  - DisposeBase
  - NopDisposable
  - RefCountDisposable
  - ScheduledDisposable
  - SerialDisposable
  - SingleAssignmentDisposable
  - SubscriptionDisposable
- name: RxSwift/Extensions
  children:
  - Bag+Rx
  - String+Rx
- name: RxSwift/Observables/Implementations
  children:
  - AddRef
  - Amb
  - AnonymousObservable
  - AsMaybe
  - AsSingle
  - Buffer
  - Catch
  - CombineLatest+arity
  - CombineLatest+Collection
  - CombineLatest
  - Concat
  - ConnectableObservable
  - Debounce
  - Debug
  - DefaultIfEmpty
  - Deferred
  - Delay
  - DelaySubscription
  - DistinctUntilChanged
  - Do
  - ElementAt
  - Empty
  - Error
  - Filter
  - Generate
  - GroupBy
  - Just
  - Map
  - Merge
  - Multicast
  - Never
  - ObserveOn
  - ObserveOnSerialDispatchQueue
  - Optional
  - Producer
  - Range
  - Reduce
  - RefCount
  - Repeat
  - RetryWhen
  - Sample
  - Scan
  - Sequence
  - ShareReplay1
  - ShareReplay1WhileConnected
  - SingleAsync
  - Sink
  - Skip
  - SkipUntil
  - SkipWhile
  - StartWith
  - SubscribeOn
  - Switch
  - SwitchIfEmpty
  - Take
  - TakeLast
  - TakeUntil
  - TakeWhile
  - Throttle
  - Timeout
  - Timer
  - ToArray
  - Using
  - Window
  - WithLatestFrom
  - Zip+arity
  - Zip+Collection
  - Zip
- name: RxSwift/Observables
  children:
  - Observable+Aggregate
  - Observable+Binding
  - Observable+Concurrency
  - Observable+Creation
  - Observable+Debug
  - Observable+Multiple
  - Observable+Single
  - Observable+StandardSequenceOperators
  - Observable+Time
- name: RxSwift/Observers
  children:
  - AnonymousObserver
  - ObserverBase
  - TailRecursiveSink
- name: RxSwift/Platform/DataStructures
  children:
  - Bag
  - InfiniteSequence
  - PriorityQueue
  - Queue
- name: RxSwift/Platform
  children:
  - DispatchQueue+Extensions
  - Platform.Darwin
  - Platform.Linux
  - RecursiveLock
- name: RxSwift/Schedulers
  children:
  - ConcurrentDispatchQueueScheduler
  - ConcurrentMainScheduler
  - CurrentThreadScheduler
  - HistoricalScheduler
  - HistoricalSchedulerTimeConverter
  - ImmediateScheduler
  - MainScheduler
  - OperationQueueScheduler
  - RecursiveScheduler
  - SchedulerServices+Emulation
  - SerialDispatchQueueScheduler
  - VirtualTimeConverterType
  - VirtualTimeScheduler
- name: RxSwift/Schedulers/Internal
  children:
  - AnonymousInvocable
  - DispatchQueueConfiguration
  - InvocableScheduledItem
  - InvocableType
  - ScheduledItem
  - ScheduledItemType
- name: RxSwift/Subjects
  children:
  - AsyncSubject
  - BehaviorSubject
  - PublishSubject
  - ReplaySubject
  - SubjectType
  - Variable
- name: RxSwift/Units
  children:
  - PrimitiveSequence+Zip+arity
  - PrimitiveSequence
- name: RxCocoa/CocoaUnits
  children:
  - ControlEvent
  - ControlProperty
  - UIBindingObserver
- name: RxCocoa/CocoaUnits/Driver
  children:
  - ControlEvent+Driver
  - ControlProperty+Driver
  - Driver+Subscription
  - Driver
  - ObservableConvertibleType+Driver
  - Variable+Driver
- name: RxCocoa/CocoaUnits/SharedSequence
  children:
  - ObservableConvertibleType+SharedSequence
  - SharedSequence+Operators+arity
  - SharedSequence+Operators
  - SharedSequence
  - Variable+SharedSequence
- name: RxCocoa/Common
  children:
  - ControlTarget
  - DelegateProxy
  - DelegateProxyType
  - NSLayoutConstraint+Rx
  - Observable+Bind
  - RxCocoaObjCRuntimeError+Extensions
  - RxTarget
  - SectionedViewDataSourceType
  - TextInput
- name: RxCocoa/Foundation
  children:
  - KVORepresentable+CoreGraphics
  - KVORepresentable+Swift
  - KVORepresentable
  - Logging
  - NotificationCenter+Rx
  - NSObject+Rx+KVORepresentable
  - NSObject+Rx+RawRepresentable
  - NSObject+Rx
  - URLSession+Rx
- name: RxCocoa/iOS/DataSources
  children:
  - RxCollectionViewReactiveArrayDataSource
  - RxTableViewReactiveArrayDataSource
- name: RxCocoa/iOS/Events
  children:
  - ItemEvents
- name: RxCocoa/iOS
  children:
  - NSTextStorage+Rx
  - UIActivityIndicatorView+Rx
  - UIAlertAction+Rx
  - UIApplication+Rx
  - UIBarButtonItem+Rx
  - UIButton+Rx
  - UICollectionView+Rx
  - UIControl+Rx
  - UIDatePicker+Rx
  - UIGestureRecognizer+Rx
  - UIImageView+Rx
  - UILabel+Rx
  - UINavigationItem+Rx
  - UIPageControl+Rx
  - UIPickerView+Rx
  - UIProgressView+Rx
  - UIRefreshControl+Rx
  - UIScrollView+Rx
  - UISearchBar+Rx
  - UISearchController+Rx
  - UISegmentedControl+Rx
  - UISlider+Rx
  - UIStepper+Rx
  - UISwitch+Rx
  - UITabBar+Rx
  - UITabBarController+Rx
  - UITabBarItem+Rx
  - UITableView+Rx
  - UITextField+Rx
  - UITextView+Rx
  - UIView+Rx
  - UIViewController+Rx
  - UIWebView+Rx
- name: RxCocoa/iOS/Protocols
  children:
  - RxCollectionViewDataSourceType
  - RxTableViewDataSourceType
- name: RxCocoa/iOS/Proxies
  children:
  - RxCollectionViewDataSourceProxy
  - RxCollectionViewDelegateProxy
  - RxPickerViewDelegateProxy
  - RxScrollViewDelegateProxy
  - RxSearchBarDelegateProxy
  - RxSearchControllerDelegateProxy
  - RxTabBarControllerDelegateProxy
  - RxTabBarDelegateProxy
  - RxTableViewDataSourceProxy
  - RxTableViewDelegateProxy
  - RxTextStorageDelegateProxy
  - RxTextViewDelegateProxy
  - RxWebViewDelegateProxy
- name: RxCocoa/macOS
  children:
  - NSButton+Rx
  - NSControl+Rx
  - NSImageView+Rx
  - NSSlider+Rx
  - NSTextField+Rx
  - NSView+Rx
- name: RxCocoa/Platform
  children:
  - DispatchQueue+Extensions
- name: RxCocoa
  children:
  - RxCocoa
