---
custom_categories:
- name: RxSwift
  children:
  - Cancelable
  - GroupedObservable
  - RxMutableBox
  - Event
  - AnyObserver
  - Disposable
  - ObservableType+Extensions
  - ObserverType
  - Reactive
  - Deprecated
  - ObservableConvertibleType
  - Observable
  - SchedulerType
  - ConnectableObservableType
  - ObservableType
  - Errors
  - Rx
  - ImmediateSchedulerType
- name: RxSwift/Traits
  children:
  - Completable+AndThen
  - PrimitiveSequence
  - PrimitiveSequence+Zip+arity
- name: RxSwift/Platform
  children:
  - Platform.Darwin
  - DispatchQueue+Extensions
  - Platform.Linux
  - RecursiveLock
- name: RxSwift/Platform/DataStructures
  children:
  - Bag
  - PriorityQueue
  - Queue
  - InfiniteSequence
- name: RxSwift/Disposables
  children:
  - DisposeBase
  - DisposeBag
  - ScheduledDisposable
  - NopDisposable
  - SubscriptionDisposable
  - RefCountDisposable
  - CompositeDisposable
  - SingleAssignmentDisposable
  - SerialDisposable
  - BinaryDisposable
  - AnonymousDisposable
  - BooleanDisposable
  - Disposables
- name: RxSwift/Observables
  children:
  - AsMaybe
  - Timeout
  - Never
  - RetryWhen
  - Do
  - Deferred
  - Buffer
  - SubscribeOn
  - DefaultIfEmpty
  - Using
  - Delay
  - Producer
  - GroupBy
  - Concat
  - Take
  - TakeWhile
  - TakeLast
  - Error
  - CombineLatest
  - Sample
  - AsSingle
  - Empty
  - Enumerated
  - DistinctUntilChanged
  - First
  - Timer
  - AddRef
  - Sequence
  - Sink
  - Throttle
  - Range
  - WithLatestFrom
  - ObserveOn
  - CombineLatest+Collection
  - Multicast
  - SkipWhile
  - DelaySubscription
  - Repeat
  - ToArray
  - TakeUntil
  - Switch
  - Window
  - Debounce
  - Dematerialize
  - Zip+Collection
  - Catch
  - Filter
  - Amb
  - Reduce
  - CombineLatest+arity
  - Zip
  - Debug
  - Merge
  - Skip
  - Map
  - SkipUntil
  - StartWith
  - Just
  - Optional
  - Generate
  - ShareReplayScope
  - Scan
  - Zip+arity
  - SwitchIfEmpty
  - ElementAt
  - Create
  - Materialize
  - SingleAsync
- name: RxSwift/Extensions
  children:
  - Bag+Rx
  - String+Rx
- name: RxSwift/Concurrency
  children:
  - LockOwnerType
  - SynchronizedDisposeType
  - SynchronizedOnType
  - Lock
  - AsyncLock
  - SynchronizedUnsubscribeType
- name: RxSwift/Subjects
  children:
  - SubjectType
  - BehaviorSubject
  - AsyncSubject
  - ReplaySubject
  - PublishSubject
  - Variable
- name: RxSwift/Observers
  children:
  - ObserverBase
  - TailRecursiveSink
  - AnonymousObserver
- name: RxSwift/Schedulers
  children:
  - RecursiveScheduler
  - OperationQueueScheduler
  - VirtualTimeScheduler
  - SchedulerServices+Emulation
  - CurrentThreadScheduler
  - MainScheduler
  - ConcurrentDispatchQueueScheduler
  - ConcurrentMainScheduler
  - SerialDispatchQueueScheduler
  - HistoricalScheduler
  - VirtualTimeConverterType
  - HistoricalSchedulerTimeConverter
- name: RxSwift/Schedulers/Internal
  children:
  - ScheduledItem
  - InvocableType
  - InvocableScheduledItem
  - DispatchQueueConfiguration
  - ScheduledItemType
- name: RxCocoa/macOS
  children:
  - NSView+Rx
  - NSButton+Rx
  - NSTextField+Rx
  - NSControl+Rx
  - NSSlider+Rx
  - NSImageView+Rx
- name: RxCocoa/Traits
  children:
  - ControlEvent
  - UIBindingObserver
  - ControlProperty
- name: RxCocoa/Traits/Driver
  children:
  - Driver+Subscription
  - ObservableConvertibleType+Driver
  - Variable+Driver
  - Driver
  - ControlEvent+Driver
  - ControlProperty+Driver
- name: RxCocoa/Traits/SharedSequence
  children:
  - SharedSequence
  - SharedSequence+Operators+arity
  - Variable+SharedSequence
  - SharedSequence+Operators
  - ObservableConvertibleType+SharedSequence
- name: RxCocoa/Platform
  children:
  - DispatchQueue+Extensions
- name: RxCocoa/Foundation
  children:
  - NSObject+Rx+KVORepresentable
  - Logging
  - KVORepresentable
  - NSObject+Rx+RawRepresentable
  - NotificationCenter+Rx
  - KVORepresentable+CoreGraphics
  - KVORepresentable+Swift
  - NSObject+Rx
  - URLSession+Rx
- name: RxCocoa/iOS/DataSources
  children:
  - RxPickerViewAdapter
  - RxCollectionViewReactiveArrayDataSource
  - RxTableViewReactiveArrayDataSource
- name: RxCocoa/iOS
  children:
  - UIDatePicker+Rx
  - UIScrollView+Rx
  - UIApplication+Rx
  - UISegmentedControl+Rx
  - UITextView+Rx
  - UIRefreshControl+Rx
  - UIImageView+Rx
  - UILabel+Rx
  - UITabBarItem+Rx
  - NSTextStorage+Rx
  - UIProgressView+Rx
  - UITabBarController+Rx
  - UIWebView+Rx
  - UITextField+Rx
  - UISearchBar+Rx
  - UIAlertAction+Rx
  - UISlider+Rx
  - UIPickerView+Rx
  - UIView+Rx
  - UIButton+Rx
  - UISearchController+Rx
  - UITabBar+Rx
  - UISwitch+Rx
  - UIPageControl+Rx
  - UIViewController+Rx
  - UICollectionView+Rx
  - UIActivityIndicatorView+Rx
  - UITableView+Rx
  - UIGestureRecognizer+Rx
  - UIStepper+Rx
  - UINavigationController+Rx
  - UIControl+Rx
  - UIBarButtonItem+Rx
  - UINavigationItem+Rx
- name: RxCocoa/iOS/Proxies
  children:
  - RxPickerViewDelegateProxy
  - RxTableViewDelegateProxy
  - RxNavigationControllerDelegateProxy
  - RxSearchControllerDelegateProxy
  - RxTabBarControllerDelegateProxy
  - RxCollectionViewDelegateProxy
  - RxScrollViewDelegateProxy
  - RxPickerViewDataSourceProxy
  - RxTableViewDataSourceProxy
  - RxSearchBarDelegateProxy
  - RxCollectionViewDataSourceProxy
  - RxWebViewDelegateProxy
  - RxTextViewDelegateProxy
  - RxTextStorageDelegateProxy
  - RxTabBarDelegateProxy
- name: RxCocoa/iOS/Events
  children:
  - ItemEvents
- name: RxCocoa/iOS/Protocols
  children:
  - RxPickerViewDataSourceType
  - RxCollectionViewDataSourceType
  - RxTableViewDataSourceType
- name: RxCocoa/Common
  children:
  - NSLayoutConstraint+Rx
  - DelegateProxy
  - RxCocoaObjCRuntimeError+Extensions
  - TextInput
  - SectionedViewDataSourceType
  - ControlTarget
  - Observable+Bind
  - RxTarget
  - DelegateProxyType
- name: RxCocoa
  children:
  - Deprecated
  - RxCocoa
