// This file is autogenerated. Take a look at `Preprocessor` target in RxSwift project 
//
//  NAryDisposable.swift
//  RxSwift
//
//  Created by Krunoslav Zaher on 8/20/15.
//  Copyright © 2015 Krunoslav Zaher. All rights reserved.
//

import Foundation
